In [1]:
import numpy as np

In [11]:
l=[1,2,3,4] #python list
a=np.array([1,2,3,4])  # numpy array

print(l,type(l))
print(a,type(a))

[1, 2, 3, 4] <class 'list'>
[1 2 3 4] <class 'numpy.ndarray'>


In [15]:
 # broadcsting , i.e adding 1 to all numbers
#possible only with numpy arrays and not with list or normal arrays
print(a+1)
print(a**2)
print(a*2)

[2 3 4 5]
[ 1  4  9 16]
[2 4 6 8]


In [22]:
#creating a 2d matrix
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [24]:
b.shape   #gives rows and cols

(2, 3)

In [36]:
b=b.reshape((6,1))
print(b,"\n")
b=b.reshape((6,))
print(b,"\n")
b=b.reshape((3,2))
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] 

[1 2 3 4 5 6] 

[[1 2]
 [3 4]
 [5 6]]


In [48]:
a=np.zeros((5,4),dtype='int')
a[1:4,1:3]=5    # row 1 to 3 and col 1 to 2 get value 5
print(a)


[[0 0 0 0]
 [0 5 5 0]
 [0 5 5 0]
 [0 5 5 0]
 [0 0 0 0]]


In [49]:
#a[ nothing specified so all rows will be selected : col index (x) or col range(a:b) ]
a[ : , -1]=7
print(a)

[[0 0 0 7]
 [0 5 5 7]
 [0 5 5 7]
 [0 5 5 7]
 [0 0 0 7]]


In [125]:
b=np.ones((5,4),dtype='int')*9+8
print(b)

[[17 17 17 17]
 [17 17 17 17]
 [17 17 17 17]
 [17 17 17 17]
 [17 17 17 17]]


In [126]:
#horizontal combination by hstack and vertial by vstack
#to get transpose use .T
c=np.vstack((a,b))          # for this to work number of cols of both a and b should be same
print(c)                    # and in case of horizontal stack nuumber of rows should be same
print(c.shape)

[[ 0  0  0  7]
 [ 0  5  5  7]
 [ 0  5  5  7]
 [ 0  5  5  7]
 [ 0  0  0  7]
 [17 17 17 17]
 [17 17 17 17]
 [17 17 17 17]
 [17 17 17 17]
 [17 17 17 17]]
(10, 4)


In [53]:
arr=np.array([39,4,92,49,94])

In [56]:
print(arr.max())
print(arr.min())
print(arr.argmax())    # gives index of maxm element
print(arr.argmin())    # gives index of minm element

94
4
4
1


In [60]:
arr.mean()    # to calculate mean

55.6

In [61]:
arr.std()  #standard deviation

34.003529228596264

In [66]:
no=np.random.random()
print(no)

0.5911193213114688


In [75]:
no=np.round(np.random.random())*5+8
print(no)

13.0


In [95]:
np.random.randint(10,100,size=(2,3)) # generate random number between range 10 to 100 in 2 rows and 3 cols

array([[31, 24, 38],
       [36, 87, 60]])

In [96]:
np.random.randn(3,3)     # gives normal distribution

array([[-0.43350211,  0.27898648, -0.13511012],
       [-0.19944922,  1.28881186, -1.11342592],
       [-1.19308657,  1.51780215,  1.20341727]])

In [131]:
arr=np.random.randn(10,10)
arr[:3]

array([[ 1.26960281, -0.58573805, -0.02042392, -0.54490259, -0.46287765,
         1.27662639, -0.11212466, -0.30833392,  0.96271905, -0.60137265],
       [-2.33496092, -0.18683143, -0.25425967, -0.8078202 , -0.2833452 ,
        -1.4243654 ,  0.04844283,  0.82060175,  0.45151424, -0.0055187 ],
       [-0.61558057, -0.66749379,  1.24967819, -1.43143726, -0.5618804 ,
        -0.3852002 , -1.29899106, -0.89899234, -1.65578894, -0.19309139]])

In [132]:
arr.mean()

-0.10709385640953985

In [156]:
print("standard deviation",arr.std()) 
print()
arr=arr.reshape(25,-1)    # placing -1 there tells the compiler to choose the n.o of colmns accordingly
print(arr)
arr.shape

standard deviation 1.0292971529807158

[[ 1.26960281 -0.58573805 -0.02042392 -0.54490259]
 [-0.46287765  1.27662639 -0.11212466 -0.30833392]
 [ 0.96271905 -0.60137265 -2.33496092 -0.18683143]
 [-0.25425967 -0.8078202  -0.2833452  -1.4243654 ]
 [ 0.04844283  0.82060175  0.45151424 -0.0055187 ]
 [-0.61558057 -0.66749379  1.24967819 -1.43143726]
 [-0.5618804  -0.3852002  -1.29899106 -0.89899234]
 [-1.65578894 -0.19309139  1.29908823  0.30912538]
 [-1.27753525 -1.53034974 -1.83994596  0.30560323]
 [ 0.47962099 -1.07561843 -0.57550623  0.97105222]
 [-0.56790222  2.14451579  1.43348916 -0.08740316]
 [ 0.24015058  0.63408484 -1.73943292  0.67420416]
 [ 1.40678951 -1.25811715  1.21211167 -1.17748724]
 [-0.81230429 -0.172224    0.593989   -0.58808518]
 [-0.77327276  0.60927847  0.63185197 -0.84252119]
 [-0.31907015 -1.2318723  -1.41605649 -2.73875263]
 [-1.37735523 -0.40319961  0.99701841  1.66083209]
 [-0.14283604  0.77398909 -0.28458303 -1.39496211]
 [ 2.32820434 -0.45052281  0.28480997 -0.56

(25, 4)

In [153]:
arr=arr.reshape(100,)  
print(arr)
arr.shape

[ 1.26960281 -0.58573805 -0.02042392 -0.54490259 -0.46287765  1.27662639
 -0.11212466 -0.30833392  0.96271905 -0.60137265 -2.33496092 -0.18683143
 -0.25425967 -0.8078202  -0.2833452  -1.4243654   0.04844283  0.82060175
  0.45151424 -0.0055187  -0.61558057 -0.66749379  1.24967819 -1.43143726
 -0.5618804  -0.3852002  -1.29899106 -0.89899234 -1.65578894 -0.19309139
  1.29908823  0.30912538 -1.27753525 -1.53034974 -1.83994596  0.30560323
  0.47962099 -1.07561843 -0.57550623  0.97105222 -0.56790222  2.14451579
  1.43348916 -0.08740316  0.24015058  0.63408484 -1.73943292  0.67420416
  1.40678951 -1.25811715  1.21211167 -1.17748724 -0.81230429 -0.172224
  0.593989   -0.58808518 -0.77327276  0.60927847  0.63185197 -0.84252119
 -0.31907015 -1.2318723  -1.41605649 -2.73875263 -1.37735523 -0.40319961
  0.99701841  1.66083209 -0.14283604  0.77398909 -0.28458303 -1.39496211
  2.32820434 -0.45052281  0.28480997 -0.56994645 -0.54688286 -1.11437893
  1.2794286  -1.49807179  0.51505897  0.31239879 -0.1

(100,)

In [107]:
# shifting mean and standard deviation ,say to 10
arr=np.random.randn(10,10)+10
print(arr.mean())
print(arr.std())


9.934946957335328
1.0333129572514062


In [112]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1,2,3]]).reshape(3,1)
print(arr1.shape,arr2.shape)

(2, 3) (3, 1)


In [113]:
# TAKING DOT PRODUCT OF TWO ARRAYS
np.dot(arr1,arr2)

array([[14],
       [32]])

In [114]:
arr1=np.array([1,2,3,4])

print(np.sin(arr1))
print(np.log(arr1))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]


In [122]:
arr1=np.random.randint(0,100,size=(5,5))
print(arr1)
np.linalg.inv(arr1)   # finding inverse of matrix arr1

[[47 17 40 37 74]
 [19 12  7 83 59]
 [43 72  0 96 64]
 [57 56  6 27 44]
 [21 35 52 74 63]]


array([[-0.08507632,  0.09390426, -0.11375478,  0.12820459,  0.03800953],
       [ 0.03380984, -0.05718243,  0.06003419, -0.04946336, -0.01260262],
       [-0.03507067,  0.022731  , -0.04771987,  0.04328338,  0.03815403],
       [-0.05961389,  0.06003073, -0.05973702,  0.06296928,  0.03051009],
       [ 0.10854541, -0.08880778,  0.11412105, -0.12494509, -0.05712484]])